# Site settings
title: "Beck + Jon"
description: |
    August 17, 2019
owner: Dan Abrey
first_published: 2018
email: danabrey@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "beckandjon.com" # the base hostname & protocol for your site

social:
  email: wedding@beckandjon.com

# Build settings
markdown: kramdown
