# Site settings
title: "Beck + Jon"
description: |
    August 15, 2020
owner: Dan Abrey
first_published: 2018
email: danabrey@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.beckandjon.com" # the base hostname & protocol for your site

social:
  github: https://github.com/danabrey/beckandjon.com

# Build settings
markdown: kramdown
